-- Day 1 Bootcamp Assignment: Lakebase Support Ticket App
-- Execute this file through the Databricks App's database connection so the
-- App service principal owns the support_app schema and its objects.

CREATE SCHEMA IF NOT EXISTS support_app;

CREATE TABLE IF NOT EXISTS support_app.tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_by TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tickets_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT tickets_created_by_not_blank CHECK (btrim(created_by) <> ''),
    CONSTRAINT tickets_status_allowed CHECK (
        status IN ('open', 'in_progress', 'resolved')
    )
);

CREATE TABLE IF NOT EXISTS support_app.ticket_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    message_text TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ticket_messages_text_not_blank CHECK (btrim(message_text) <> ''),
    CONSTRAINT ticket_messages_author_not_blank CHECK (btrim(author) <> ''),
    CONSTRAINT ticket_messages_ticket_fk
        FOREIGN KEY (ticket_id)
        REFERENCES support_app.tickets(ticket_id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_tickets_status_created_at
    ON support_app.tickets (status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_created_at
    ON support_app.ticket_messages (ticket_id, created_at);

-- Fixed high IDs make this seed block safe to re-run without colliding with
-- ordinary identity-generated rows during the assignment.
INSERT INTO support_app.tickets (
    ticket_id,
    title,
    status,
    created_by,
    created_at
)
VALUES
    (1001, 'Cannot access the analytics dashboard', 'open', 'alice', CURRENT_TIMESTAMP - INTERVAL '3 hours'),
    (1002, 'Scheduled report failed to run', 'in_progress', 'bob', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
    (1003, 'Request access to the finance workspace', 'resolved', 'carol', CURRENT_TIMESTAMP - INTERVAL '1 hour')
ON CONFLICT (ticket_id) DO NOTHING;

INSERT INTO support_app.ticket_messages (
    message_id,
    ticket_id,
    message_text,
    author,
    created_at
)
VALUES
    (2001, 1001, 'The dashboard returns an authorization error.', 'alice', CURRENT_TIMESTAMP - INTERVAL '170 minutes'),
    (2002, 1001, 'Support is checking the workspace permissions.', 'support_agent', CURRENT_TIMESTAMP - INTERVAL '160 minutes'),
    (2003, 1002, 'The 08:00 report did not produce an output file.', 'bob', CURRENT_TIMESTAMP - INTERVAL '110 minutes'),
    (2004, 1002, 'The job logs show a source connection timeout.', 'support_agent', CURRENT_TIMESTAMP - INTERVAL '100 minutes'),
    (2005, 1003, 'Please grant read access to the finance workspace.', 'carol', CURRENT_TIMESTAMP - INTERVAL '50 minutes'),
    (2006, 1003, 'Access was granted and confirmed by the requester.', 'support_agent', CURRENT_TIMESTAMP - INTERVAL '40 minutes')
ON CONFLICT (message_id) DO NOTHING;
